### ISSUE TITLE
Shepard Plus panels only showing "outputs"

### ISSUE THREAD

**Issue by tubalainen** [shprota/home_assistant_crow#3]
Hi!

I was sooo excited when I found this custom component! Just got my Shepard Plus system installed.
It all adds fine, but only three "output" entities shown from the integration. Two Sirens and my Yale Doorman module.
![image](https://github.com/shprota/home_assistant_crow/assets/26795429/c0e39060-3128-4e6f-b25b-7b9c8487a714)

I would be happy to provide user/pass/mac to you dev guys if you would find the time to update this component. :)
Thanks a billion! <3

**Comment by t112013** [comment]
I completly agree, i actually i only need to add the changed_by field :( 
i would really love some of the devs to have a quick look
cheers

**Comment by tubalainen** [comment]
> I completly agree, i actually i only need to add the changed_by field :( i would really love some of the devs to have a quick look cheers

Oh ok, where can I find the "changed_by field" i the code?

**Comment by shprota** [comment]
@tubalainen Please elaborate, what is missing from the integration. In the current state the Crow API only supports reading some sensors and controlling the alarm state and the outputs.

**Comment by t112013** [comment]
is not possible to get the status ? 
In the app there is a fiels that says like "armed by xxxx" 
That would help a lot :)

**Comment by tubalainen** [comment]
> @tubalainen Please elaborate, what is missing from the integration. In the current state the Crow API only supports reading some sensors and controlling the alarm state and the outputs.

Hi @shprota! Absolutely - love to!
Ive got a brand new Crow Shepard Plus panel that runs on firmware 0.9.84.93.

**Issue 1.)**
When I joins it to this component it exposes three switches (my sirens + Yale Doorman) only (according to the component)
![image](https://github.com/shprota/home_assistant_crow/assets/26795429/c1b3e47e-4197-4c37-a378-65aaf9c83d2a)
![image](https://github.com/shprota/home_assistant_crow/assets/26795429/8502c2b9-0ce2-41e1-af3c-3c4e34cf8041)

Where is the `alarm_panel` entity? It is not being listed as part of the component. The alarm_panel entity is being added and it works fine.

**Proposal/improvements/issue 2.)**
When joining my system to the component no sensors are presented/created.
I would love to see lock, binary_sensors, sensors and cameras to gain full access and capability of what the API is providing.

The Verisure alarm component of home assistant is the most "mature" if you ask me, we could perhaps copy/steal with pride from that component to leverage the features from that one?

**Comment by tubalainen** [comment]
> is not possible to get the status ? In the app there is a fiels that says like "armed by xxxx" That would help a lot :)

Yes! :)

After you have added the component an entity starting with `alarm_panel.` will be created.
You can then based on the state of that do automations. Here is an example, if the alarm system is armed home or armed away and a person trips the cameras the floodlights + lawn sprinklers will turn on:
```
- id: 'zone1_on_if_motion'
  alias: "Zone 1 bevattning om rörelse nattetid"
  initial_state: 'off'
  trigger:
    entity_id:
      - binary_sensor.cam1_framsidan_all_occupancy
      - binary_sensor.cam3_framsidan_all_occupancy
      - binary_sensor.shelly_11_switch
    platform: state
    to: "on"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '23:00:00'
        before: '05:30:00'
      - condition: state
        entity_id: binary_sensor.helga_laddar
        state: "on"
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.sikvagen_11_hemma
            state: armed_away
          - condition: state
            entity_id: alarm_control_panel.sikvagen_11_hemma
            state: armed_home
  action:
      ## Turn on floodlights + lawn sprinklers
    - data:
        entity_id:
          - switch.zone1_valve #Spridarna på
          - switch.shelly2_04_relay_1 #Floodlights Altanten
          - switch.shelly_04_relay #Floodlights Köket
          - switch.shelly_11_relay #Floodlights finentren
      service: switch.turn_on 
    - delay: "00:00:05"
      ## Send notification to phone with picture of the wet mamal.
    - data_template:
        message: Vattenspridarna triggades nattetid
        data:
          image: https://xxxx.ui.nabu.casa/api/camera_proxy/camera.cam3_framsidan?token={{ state_attr("camera.cam3_framsidan", "access_token") }}
          ttl: 0
          priority: high
      service: notify.mobile_app_pixel_7_pro
    - delay: "00:00:20"
      ## Turn off and reset
    - data:
        entity_id:
          - switch.shelly2_04_relay_1 #Altanten
          - switch.shelly_04_relay #Köket
          - switch.shelly_11_relay #finentren
          - switch.zone1_valve #Spridarna av
      service: switch.turn_off
```
